### PR TITLE
fix: fix certificate lookup bugs in CertificateResolver

### LINKED ISSUE #774: Could not look up a certificate for server name 'domain'
I just installed sozu and setup my config as follows:

```
[[listeners]]
address = "0.0.0.0:443"
protocol = "https"
tls_versions = ["TLSv1.2", "TLSv1.3"]
cipher_list = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"

[applications]

[applications.AppName]
protocol = "http"
https_redirect = true

frontends = [
  { address = "127.0.0.1:1444", hostname = "domain", certificate = "/etc/domain/cert.pem", key = "/etc/domain/key.pem", certificate_chain = "/etc/cloudflare/chain.pem" }
]

backends  = [
  { address = "127.0.0.1:444" }
]
```

But when I access my domain from the browser I get the following error:
```
could not look up a certificate for server name 'domain'
Sending fatal alert AccessDenied
could not perform handshake: General("no server certificate chain resolved")
```

### PR DESCRIPTION
**Pull request by FlorentinDUBOIS**
## Summary

Two interacting bugs in `lib/src/tls.rs` causing wrong certificate selection and memory leaks. The third fix from the original PR (`try_lock()` → blocking `lock()`) was shipped independently on `main` during the h2-mux integration trail and is therefore dropped from this PR's scope after rebase.

1. **Remove-before-add in `replace_certificate()`** — Old cert was removed before new cert was added. If the add failed, the old cert was already gone. Reversed order: add new first, remove old second.
2. **Memory leak in `name_fingerprint_idx`** — Empty `Vec` entries were left in the HashMap after certificate removal. Added cleanup of empty entries. Replaced `drain().filter().collect()` with `retain()`.

2 new unit tests added.

Closes #774

## Test plan
- [x] `cargo test -p sozu-lib --all-features --locked tls::` — 8/8 pass (including 2 new tests)
- [x] `cargo build --all-features --locked` clean
- [x] `cargo clippy --all-targets --all-features --locked -- -D warnings` clean (matches CI gate `.github/workflows/ci.yml:47`)
- [x] `cargo +nightly fmt --all -- --check` clean

### CODE REVIEW

File: lib/src/tls.rs [hunk 1]
```diff
@@ -224,21 +224,27 @@ impl CertificateResolver {
...
-                        .filter(|t| &t.0 != fingerprint)
-                        .collect();
+                    fingerprints_and_exp.retain(|t| &t.0 != fingerprint);
 
-                    // if present, reinsert the longest lived certificate in the TrieNode
+                    // reinsert the longest lived certificate in the TrieNode
                     if let Some(longest_lived_cert) = fingerprints_and_exp.last() {
                         self.domains
-                            .insert(name.into_bytes(), longest_lived_cert.0.to_owned());
+                            .insert(name.as_bytes().to_vec(), longest_lived_cert.0.to_owned());
```
Comment (llenotre) [inline lib/src/tls.rs]: useless change, gives the same result
